SELECT TOP (1000) [CompanyID]
      ,[SalespersonID]
      ,[SalespersonCD]
      ,[CommnPct]
      ,[SalesSubID]
      ,[tstamp]
      ,[CreatedByID]
      ,[CreatedByScreenID]
      ,[CreatedDateTime]
      ,[LastModifiedByID]
      ,[LastModifiedByScreenID]
      ,[LastModifiedDateTime]
      ,[Descr]
      ,[IsActive]
      ,[NoteID]
  FROM [2024R2DEV].[dbo].[SalesPerson]
